---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  #name: chef_solo

platforms:
  - name: centos/7
  #- name: centos-7.1
  #- name: centos-7.2

suites:
  - name: default
    driver:
      vm_hostname: edgemicro.com
      network:
        #change the IP address to a unique IP in the same network range as the hosts interface IP
      - ["public_network", {ip: "192.168.99.120", bridge: "en0: Wi-Fi (AirPort)"}]
    run_list:
      - recipe[edgemicro]
    attributes:
