---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  #name: chef_solo

platforms:
  - name: centos/7
  #- name: centos-7.1
  #- name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[edgemicro]
    attributes:
